Shapes in microstructures
SwanLab/Swan pull request #180
Opened 2022-07-19 08:51 UTC by JoelCarrasc0

2022-07-19 10:28 UTC, FerrerFerreAlex commented
@tcreusc

2022-07-19 16:45 UTC, tcreusc reviewed
Since some input files had been deleted, I changed them for other base meshes. I don't know if the data that is loaded through .mat files still applies properly (also, it may be interesting to find a more elegant way to load this data -- perhaps it's a case to consider when refactoring the TopOpt Settings one of these days)

Btw, does anyone know if the Isotropy tests increase the code coverage? If so, we could include them as new TopOptTests; otherwise, I think leaving them as examples is fine.

2022-07-25 14:05 UTC, tcreusc requested changes

2022-09-05 12:38 UTC, tcreusc commented
UML
![imatge](https://user-images.githubusercontent.com/24914481/188451074-679269f6-4ab4-471e-80c8-c7827b279733.png)

2022-09-05 12:44 UTC, merged